### ISSUE TITLE
getProcess is called 1 fewer times than other get methods. 

### ISSUE THREAD

**Issue by BradleyLamitie** [HarshaKota/MSCS-710L-Project#9] opened 2018-11-07 03:10 UTC
Console returns:
  getPower calls:  1
    getMemory calls:  1
   getSensors calls:  1
       getCPU calls:  1
   getProcess calls:  0
   getNetwork calls:  1

**Comment by HarshaKota** [comment] 2018-11-07 05:06
@BradleyLamitie, run the program and check if the issue is re-occurring. If not, close this issue.

**Comment by HarshaKota** [comment] 2018-11-08 01:05
I've checked it again on 2 different systems, I cannot replicate it. I think it got fixed with the commit
c8190296209648f94da664667bcfb6e0fe8eaf24

**Closed by HarshaKota** 2018-11-08 01:05 UTC
Labels: bug
